"""Script untuk mengganti teks China ke Indonesia"""

# Mapping terjemahan
translations = {
    # Docstrings dan comments
    "数据库实现": "Implementasi Database",
    "使用SQLite3进行数据存储，无需额外安装数据库服务器": "Menggunakan SQLite3 untuk penyimpanan data, tidak perlu install database server terpisah",
    "数据库管理类": "Class Manajemen Database",
    "初始化数据库连接": "Inisialisasi koneksi database",
    "SQLite 数据库初始化": "Inisialisasi Database SQLite",
    "获取数据库连接": "Mendapatkan koneksi database",
    "使结果可以按列名访问": "Membuat hasil bisa diakses berdasarkan nama kolom",
    "初始化数据库表结构": "Inisialisasi struktur tabel database",
    "数据库表初始化完成": "Inisialisasi tabel database selesai",
    "初始化数据库失败": "Gagal inisialisasi database",
    "创建新用户": "Membuat user baru",
    "创建用户失败": "Gagal membuat user",
    "获取用户信息": "Mendapatkan info user",
    "检查用户是否存在": "Cek apakah user exists",
    "检查用户是否被拉黑": "Cek apakah user diblacklist",
    "拉黑用户": "Blacklist user",
    "拉黑用户失败": "Gagal blacklist user",
    "取消拉黑用户": "Unblacklist user",
    "取消拉黑失败": "Gagal unblacklist",
    "获取黑名单列表": "Mendapatkan daftar blacklist",
    "增加用户积分": "Tambah token user",
    "增加积分失败": "Gagal tambah token",
    "扣除用户积分": "Kurangi token user",
    "扣除积分失败": "Gagal kurangi token",
    "检查用户今天是否可以签到": "Cek apakah user bisa checkin hari ini",
    "用户签到": "User checkin",
    "签到失败": "Gagal checkin",
    "添加验证记录": "Tambah record verifikasi",
    "添加验证记录失败": "Gagal tambah record verifikasi",
    "获取用户的验证记录": "Mendapatkan record verifikasi user",
    "创建卡密": "Membuat card key",
    "卡密已存在": "Card key sudah ada",
    "创建卡密失败": "Gagal membuat card key",
    "使用卡密，返回获得的积分数量": "Gunakan card key, return jumlah token yang didapat",
    "使用卡密失败": "Gagal gunakan card key",
    "获取卡密信息": "Mendapatkan info card key",
    "获取所有卡密（可按创建者筛选）": "Mendapatkan semua card key (bisa filter by creator)",
    "获取所有用户ID": "Mendapatkan semua user ID",
    
    # User commands messages
    "用户命令处理器": "Handler Command User",
    "处理 /start 命令 - Whitelist模式，只有管理员和已注册用户能访问": "Handle command /start - Mode whitelist, hanya admin dan user terdaftar bisa akses",
    "您已被封禁，无法使用此机器人。": "Anda telah dibanned, tidak bisa menggunakan bot ini.",
    "如有疑问，请联系管理员。": "Jika ada pertanyaan, hubungi admin.",
    "欢迎回来": "Selamat datang kembali",
    "当前Token": "Token saat ini",
    "发送 /help 查看可用命令。": "Kirim /help untuk melihat command yang tersedia.",
    "管理员账户已创建！": "Akun admin telah dibuat!",
    "使用 /addbalance 添加用户": "Gunakan /addbalance untuk menambah user",
    "使用 /ban 和 /unban 管理权限": "Gunakan /ban dan /unban untuk kelola permission",
    "此机器人采用白名单模式。": "Bot ini menggunakan mode whitelist.",
    "您需要管理员授权才能使用。": "Anda perlu autorisasi admin untuk menggunakan.",
    "您的User ID": "User ID Anda",
    "请将User ID发送给管理员以获取访问权限。": "Silakan kirim User ID ke admin untuk mendapat akses.",
    "处理 /about 命令": "Handle command /about",
    "处理 /help 命令": "Handle command /help",
    "处理 /balance 命令": "Handle command /balance",
    "您已被封禁，无法使用此功能。": "Anda telah dibanned, tidak bisa menggunakan fitur ini.",
    "请先联系管理员注册。": "Silakan hubungi admin untuk registrasi terlebih dahulu.",
    "Token余额": "Saldo Token",
    "当前Token：": "Token Saat Ini:",
    
    # Admin commands messages
    "管理员命令处理器": "Handler Command Admin",
    "处理 /adduser 命令 - 管理员添加新用户": "Handle command /adduser - Admin menambah user baru",
    "您没有权限使用此命令。": "Anda tidak punya izin untuk menggunakan command ini.",
    "使用方法": "Cara penggunaan",
    "示例": "Contoh",
    "用户不存在。": "User tidak ada.",
    "用户 {target_user_id} 已经存在": "User sudah ada",
    "成功添加用户！": "Berhasil menambah user!",
    "用户ID": "User ID",
    "用户名": "Username",
    "未设置": "Tidak diset",
    "全名": "Nama lengkap",
    "初始Token": "Token awal",
    "添加用户失败，请稍后重试。": "Gagal menambah user, silakan coba lagi nanti.",
    "参数格式错误，用户ID必须是数字。": "Format parameter salah, User ID harus angka.",
    "处理 /addbalance 命令 - 管理员增加积分": "Handle command /addbalance - Admin menambah token",
    "成功为用户": "Berhasil untuk user",
    "增加": "menambah",
    "积分": "token",
    "当前积分": "Token saat ini",
    "操作失败，请稍后重试。": "Operasi gagal, silakan coba lagi nanti.",
    "参数格式错误，请输入有效的数字。": "Format parameter salah, silakan input angka yang valid.",
    "处理 /ban 命令 - 管理员封禁用户": "Handle command /ban - Admin ban user",
    "已封禁用户": "User telah dibanned",
    "参数格式错误，请输入有效的用户ID。": "Format parameter salah, silakan input User ID yang valid.",
    "处理 /unban 命令 - 管理员解除封禁": "Handle command /unban - Admin unban user",
    "已解除封禁用户": "User telah di-unban",
    "处理 /blacklist 命令 - 查看黑名单": "Handle command /blacklist - Lihat blacklist",
    "黑名单列表": "Daftar Blacklist",
    "共": "Total",
    "人": "orang",
    "黑名单为空": "Blacklist kosong",
    "处理 /broadcast 命令 - 群发消息": "Handle command /broadcast - Broadcast message",
    "使用方法: /broadcast <消息内容>": "Cara penggunaan: /broadcast <isi pesan>",
    "群发消息": "Broadcast Pesan",
    "正在发送...": "Sedang mengirim...",
    "成功": "Berhasil",
    "失败": "Gagal",
    "群发完成": "Broadcast selesai",
    
    # Verify commands
    "验证命令处理器": "Handler Command Verifikasi",
    "您已被拉黑，无法使用此功能。": "Anda telah diblacklist, tidak bisa menggunakan fitur ini.",
    "请先使用 /start 注册。": "Silakan registrasi menggunakan /start terlebih dahulu.",
    "无效的 SheerID 链接，请检查后重试。": "Link SheerID tidak valid, silakan cek dan coba lagi.",
    "扣除积分失败，请稍后重试。": "Gagal kurangi token, silakan coba lagi nanti.",
    "开始处理": "Mulai memproses",
    "认证": "verifikasi",
    "验证ID": "ID Verifikasi",
    "已扣除": "Telah dikurangi",
    "请稍候，这可能需要 1-2 分钟...": "Mohon tunggu, ini mungkin memakan waktu 1-2 menit...",
    "认证成功！": "Verifikasi berhasil!",
    "文档已提交，等待人工审核。": "Dokumen telah disubmit, menunggu review manual.",
    "跳转链接：": "Link redirect:",
    "认证失败：": "Verifikasi gagal:",
    "未知错误": "Error tidak diketahui",
    "已退回": "Telah dikembalikan",
    "验证过程出错": "Error saat proses verifikasi",
}

print("Mapping terjemahan telah dibuat")
print(f"Total: {len(translations)} terjemahan")
